#include "aimux/webui/resource_loader.hpp"

namespace aimux {
namespace webui {

ResourceLoader& ResourceLoader::getInstance() {
    static ResourceLoader instance;
    return instance;
}

void ResourceLoader::initialize() {
    // Clear any existing resources
    resources_.clear();

    // Initialize all embedded resources
    initializeDashboardHTML();
    initializeDashboardCSS();
    initializeDashboardJS();
}

const EmbeddedResource* ResourceLoader::getResource(const std::string& path) const {
    auto it = resources_.find(path);
    if (it != resources_.end()) {
        return it->second.get();
    }
    return nullptr;
}

bool ResourceLoader::hasResource(const std::string& path) const {
    return resources_.find(path) != resources_.end();
}

std::vector<std::string> ResourceLoader::getResourcePaths() const {
    std::vector<std::string> paths;
    paths.reserve(resources_.size());

    for (const auto& [path, resource] : resources_) {
        paths.push_back(path);
    }

    std::sort(paths.begin(), paths.end());
    return paths;
}

std::string ResourceLoader::getContentType(const std::string& extension) const {
    if (extension == ".html") return "text/html";
    if (extension == ".css") return "text/css";
    if (extension == ".js") return "application/javascript";
    if (extension == ".json") return "application/json";
    if (extension == ".png") return "image/png";
    if (extension == ".jpg" || extension == ".jpeg") return "image/jpeg";
    if (extension == ".svg") return "image/svg+xml";
    if (extension == ".ico") return "image/x-icon";

    return "application/octet-stream"; // Default
}

void ResourceLoader::addResource(const std::string& path, const std::string& data, const std::string& content_type) {
    auto resource = std::make_unique<EmbeddedResource>(data, content_type);
    resources_[path] = std::move(resource);
}

void ResourceLoader::initializeDashboardHTML() {
    const std::string html =
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Aimux Professional Dashboard</title>\n"
        "    <link rel=\"stylesheet\" href=\"/dashboard.css\">\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.min.js\"></script>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"app-container\" data-theme=\"light\">\n"
        "        <header class=\"header\">\n"
        "            <div class=\"header-content\">\n"
        "                <div class=\"logo\">\n"
        "                    <h1 class=\"logo-text\">Aimux Dashboard</h1>\n"
        "                </div>\n"
        "                <div class=\"header-controls\">\n"
        "                    <div class=\"connection-status\" id=\"connectionStatus\">\n"
        "                        <span class=\"status-dot\"></span>\n"
        "                        <span class=\"status-text\">Connected</span>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </header>\n"
        "\n"
        "        <main class=\"main-content\">\n"
        "            <section class=\"overview-section\">\n"
        "                <h2 class=\"section-title\">System Overview</h2>\n"
        "                <div class=\"overview-grid\">\n"
        "                    <div class=\"metric-card\">\n"
        "                        <div class=\"metric-header\">\n"
        "                            <h3>Active Requests</h3>\n"
        "                        </div>\n"
        "                        <div class=\"metric-value\" id=\"activeRequests\">0</div>\n"
        "                        <div class=\"metric-label\">requests/sec</div>\n"
        "                    </div>\n"
        "                    <div class=\"metric-card\">\n"
        "                        <div class=\"metric-header\">\n"
        "                            <h3>Total Requests</h3>\n"
        "                        </div>\n"
        "                        <div class=\"metric-value\" id=\"totalRequests\">0</div>\n"
        "                        <div class=\"metric-label\">today</div>\n"
        "                    </div>\n"
        "                    <div class=\"metric-card\">\n"
        "                        <div class=\"metric-header\">\n"
        "                            <h3>Success Rate</h3>\n"
        "                        </div>\n"
        "                        <div class=\"metric-value\" id=\"successRate\">0%</div>\n"
        "                        <div class=\"metric-label\">overall</div>\n"
        "                    </div>\n"
        "                    <div class=\"metric-card\">\n"
        "                        <div class=\"metric-header\">\n"
        "                            <h3>System Uptime</h3>\n"
        "                        </div>\n"
        "                        <div class=\"metric-value\" id=\"uptime\">0m</div>\n"
        "                        <div class=\"metric-label\">since start</div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </section>\n"
        "\n"
        "            <section class=\"providers-section\">\n"
        "                <h2 class=\"section-title\">Provider Status</h2>\n"
        "                <div class=\"providers-grid\" id=\"providersGrid\">\n"
        "                    <!-- Provider cards will be dynamically inserted here -->\n"
        "                </div>\n"
        "            </section>\n"
        "        </main>\n"
        "\n"
        "        <div id=\"loadingOverlay\" class=\"loading-overlay\" hidden>\n"
        "            <div class=\"loading-spinner\"></div>\n"
        "            <div class=\"loading-text\">Loading dashboard data...</div>\n"
        "        </div>\n"
        "    </div>\n"
        "\n"
        "    <script src=\"/dashboard.js\"></script>\n"
        "</body>\n"
        "</html>\n";

    addResource("/dashboard.html", html, "text/html");
}

void ResourceLoader::initializeDashboardCSS() {
    const std::string css =
        "/* Aimux Professional Dashboard CSS */\n"
        ":root[data-theme=\"light\"] {\n"
        "    --bg-primary: #ffffff;\n"
        "    --bg-secondary: #f8fafc;\n"
        "    --bg-card: #ffffff;\n"
        "    --text-primary: #1e293b;\n"
        "    --text-secondary: #64748b;\n"
        "    --border-primary: #e2e8f0;\n"
        "    --accent-primary: #2563eb;\n"
        "    --success: #10b981;\n"
        "    --error: #ef4444;\n"
        "    --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);\n"
        "}\n"
        "\n"
        ":root[data-theme=\"dark\"] {\n"
        "    --bg-primary: #0f172a;\n"
        "    --bg-secondary: #1e293b;\n"
        "    --bg-card: #1e293b;\n"
        "    --text-primary: #f1f5f9;\n"
        "    --text-secondary: #cbd5e1;\n"
        "    --border-primary: #334155;\n"
        "    --accent-primary: #3b82f6;\n"
        "    --success: #10b981;\n"
        "    --error: #ef4444;\n"
        "    --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.4);\n"
        "}\n"
        "\n"
        "* {\n"
        "    margin: 0;\n"
        "    padding: 0;\n"
        "    box-sizing: border-box;\n"
        "}\n"
        "\n"
        "body {\n"
        "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
        "    background-color: var(--bg-primary);\n"
        "    color: var(--text-primary);\n"
        "    line-height: 1.6;\n"
        "    transition: all 0.3s ease;\n"
        "}\n"
        "\n"
        ".header {\n"
        "    background-color: var(--bg-card);\n"
        "    border-bottom: 1px solid var(--border-primary);\n"
        "    box-shadow: var(--shadow-md);\n"
        "    position: sticky;\n"
        "    top: 0;\n"
        "    z-index: 100;\n"
        "}\n"
        "\n"
        ".header-content {\n"
        "    max-width: 1200px;\n"
        "    margin: 0 auto;\n"
        "    padding: 1rem 2rem;\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    align-items: center;\n"
        "}\n"
        "\n"
        ".logo-text {\n"
        "    font-size: 1.5rem;\n"
        "    font-weight: 700;\n"
        "    color: var(--accent-primary);\n"
        "}\n"
        "\n"
        ".main-content {\n"
        "    max-width: 1200px;\n"
        "    margin: 0 auto;\n"
        "    padding: 2rem;\n"
        "}\n"
        "\n"
        ".section-title {\n"
        "    font-size: 1.5rem;\n"
        "    font-weight: 600;\n"
        "    margin-bottom: 1.5rem;\n"
        "    color: var(--text-primary);\n"
        "}\n"
        "\n"
        ".overview-grid {\n"
        "    display: grid;\n"
        "    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n"
        "    gap: 1.5rem;\n"
        "    margin-bottom: 2rem;\n"
        "}\n"
        "\n"
        ".metric-card {\n"
        "    background-color: var(--bg-card);\n"
        "    border: 1px solid var(--border-primary);\n"
        "    border-radius: 0.75rem;\n"
        "    padding: 1.5rem;\n"
        "    box-shadow: var(--shadow-md);\n"
        "    transition: all 0.3s ease;\n"
        "}\n"
        "\n"
        ".metric-card:hover {\n"
        "    transform: translateY(-2px);\n"
        "    box-shadow: var(--shadow-md);\n"
        "}\n"
        "\n"
        ".metric-header h3 {\n"
        "    font-size: 0.875rem;\n"
        "    font-weight: 600;\n"
        "    color: var(--text-secondary);\n"
        "    text-transform: uppercase;\n"
        "    letter-spacing: 0.025em;\n"
        "    margin-bottom: 1rem;\n"
        "}\n"
        "\n"
        ".metric-value {\n"
        "    font-size: 2.5rem;\n"
        "    font-weight: 700;\n"
        "    color: var(--text-primary);\n"
        "    margin-bottom: 0.5rem;\n"
        "    line-height: 1;\n"
        "}\n"
        "\n"
        ".metric-label {\n"
        "    font-size: 0.875rem;\n"
        "    color: var(--text-secondary);\n"
        "}\n"
        "\n"
        ".providers-grid {\n"
        "    display: grid;\n"
        "    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n"
        "    gap: 1.5rem;\n"
        "}\n"
        "\n"
        ".provider-card {\n"
        "    background-color: var(--bg-card);\n"
        "    border: 1px solid var(--border-primary);\n"
        "    border-radius: 0.75rem;\n"
        "    padding: 1.5rem;\n"
        "    box-shadow: var(--shadow-md);\n"
        "    transition: all 0.3s ease;\n"
        "}\n"
        "\n"
        ".provider-header {\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    align-items: center;\n"
        "    margin-bottom: 1rem;\n"
        "}\n"
        "\n"
        ".provider-status {\n"
        "    display: flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "}\n"
        "\n"
        ".status-indicator {\n"
        "    width: 12px;\n"
        "    height: 12px;\n"
        "    border-radius: 50%;\n"
        "    background-color: var(--success);\n"
        "}\n"
        "\n"
        ".status-indicator.unhealthy {\n"
        "    background-color: var(--error);\n"
        "}\n"
        "\n"
        ".metric-row {\n"
        "    display: flex;\n"
        "    justify-content: space-between;\n"
        "    align-items: center;\n"
        "    padding: 0.5rem 0;\n"
        "    border-bottom: 1px solid var(--border-primary);\n"
        "}\n"
        "\n"
        ".metric-label {\n"
        "    font-size: 0.875rem;\n"
        "    color: var(--text-secondary);\n"
        "}\n"
        "\n"
        ".metric-value-small {\n"
        "    font-size: 0.875rem;\n"
        "    font-weight: 600;\n"
        "    color: var(--text-primary);\n"
        "}\n"
        "\n"
        ".provider-actions {\n"
        "    display: flex;\n"
        "    gap: 0.5rem;\n"
        "    margin-top: 1rem;\n"
        "}\n"
        "\n"
        ".btn {\n"
        "    border: none;\n"
        "    border-radius: 0.375rem;\n"
        "    padding: 0.75rem 1rem;\n"
        "    font-size: 0.875rem;\n"
        "    font-weight: 500;\n"
        "    cursor: pointer;\n"
        "    transition: all 0.3s ease;\n"
        "    display: inline-flex;\n"
        "    align-items: center;\n"
        "    justify-content: center;\n"
        "    gap: 0.5rem;\n"
        "    text-decoration: none;\n"
        "}\n"
        "\n"
        ".btn-primary {\n"
        "    background-color: var(--accent-primary);\n"
        "    color: white;\n"
        "}\n"
        "\n"
        ".btn-secondary {\n"
        "    background-color: var(--bg-secondary);\n"
        "    color: var(--text-primary);\n"
        "    border: 1px solid var(--border-primary);\n"
        "}\n"
        "\n"
        ".btn:hover {\n"
        "    transform: translateY(-1px);\n"
        "    box-shadow: var(--shadow-md);\n"
        "}\n"
        "\n"
        ".connection-status {\n"
        "    display: flex;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "    padding: 0.5rem 1rem;\n"
        "    border-radius: 2rem;\n"
        "    background-color: var(--bg-secondary);\n"
        "    border: 1px solid var(--border-primary);\n"
        "    font-size: 0.875rem;\n"
        "    transition: all 0.3s ease;\n"
        "}\n"
        "\n"
        ".status-dot {\n"
        "    width: 8px;\n"
        "    height: 8px;\n"
        "    border-radius: 50%;\n"
        "    background-color: var(--success);\n"
        "    animation: pulse 2s infinite;\n"
        "}\n"
        "\n"
        ".connection-status.disconnected .status-dot {\n"
        "    background-color: var(--error);\n"
        "    animation: none;\n"
        "}\n"
        "\n"
        "@keyframes pulse {\n"
        "    0%, 100% { opacity: 1; }\n"
        "    50% { opacity: 0.5; }\n"
        "}\n"
        "\n"
        ".loading-overlay {\n"
        "    position: fixed;\n"
        "    top: 0;\n"
        "    left: 0;\n"
        "    width: 100%;\n"
        "    height: 100%;\n"
        "    background-color: rgba(0, 0, 0, 0.7);\n"
        "    display: flex;\n"
        "    flex-direction: column;\n"
        "    align-items: center;\n"
        "    justify-content: center;\n"
        "    z-index: 2000;\n"
        "}\n"
        "\n"
        ".loading-spinner {\n"
        "    width: 40px;\n"
        "    height: 40px;\n"
        "    border: 4px solid rgba(255, 255, 255, 0.3);\n"
        "    border-radius: 50%;\n"
        "    border-top-color: white;\n"
        "    animation: spin 1s linear infinite;\n"
        "}\n"
        "\n"
        ".loading-text {\n"
        "    color: white;\n"
        "    margin-top: 1rem;\n"
        "    font-size: 0.875rem;\n"
        "}\n"
        "\n"
        "@keyframes spin {\n"
        "    to { transform: rotate(360deg); }\n"
        "}\n"
        "\n"
        "/* Responsive Design */\n"
        "@media (max-width: 768px) {\n"
        "    .header-content {\n"
        "        padding: 1rem;\n"
        "    }\n"
        "    .main-content {\n"
        "        padding: 1rem;\n"
        "    }\n"
        "    .overview-grid,\n"
        "    .providers-grid {\n"
        "        grid-template-columns: 1fr;\n"
        "        gap: 1rem;\n"
        "    }\n"
        "    .metric-value {\n"
        "        font-size: 2rem;\n"
        "    }\n"
        "    .logo-text {\n"
        "        font-size: 1.25rem;\n"
        "    }\n"
        "}\n";

    addResource("/dashboard.css", css, "text/css");
}

void ResourceLoader::initializeDashboardJS() {
    const std::string js =
        "// Aimux Professional Dashboard JavaScript\n"
        "console.log('Aimux Dashboard loading...');\n"
        "\n"
        "var dashboard = {\n"
        "    ws: null,\n"
        "    data: {\n"
        "        providers: {},\n"
        "        system: {},\n"
        "        requests: {}\n"
        "    },\n"
        "\n"
        "    init: function() {\n"
        "        console.log('Initializing dashboard...');\n"
        "        this.connectWebSocket();\n"
        "    },\n"
        "\n"
        "    connectWebSocket: function() {\n"
        "        var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
        "        var wsUrl = protocol + '//' + window.location.host + '/ws';\n"
        "\n"
        "        try {\n"
        "            this.ws = new WebSocket(wsUrl);\n"
        "\n"
        "            this.ws.onopen = function() {\n"
        "                console.log('WebSocket connected');\n"
        "                dashboard.updateConnectionStatus(true);\n"
        "            };\n"
        "\n"
        "            this.ws.onmessage = function(event) {\n"
        "                try {\n"
        "                    var data = JSON.parse(event.data);\n"
        "                    dashboard.updateUI(data);\n"
        "                } catch (error) {\n"
        "                    console.error('Error parsing data:', error);\n"
        "                }\n"
        "            };\n"
        "\n"
        "            this.ws.onclose = function() {\n"
        "                console.log('WebSocket disconnected');\n"
        "                dashboard.updateConnectionStatus(false);\n"
        "            };\n"
        "\n"
        "        } catch (error) {\n"
        "            console.error('Failed to connect WebSocket:', error);\n"
        "            dashboard.updateConnectionStatus(false);\n"
        "        }\n"
        "    },\n"
        "\n"
        "    updateUI: function(data) {\n"
        "        this.data = data;\n"
        "        this.updateOverviewCards();\n"
        "        this.updateProviderCards();\n"
        "        this.updateSystemResources();\n"
        "    },\n"
        "\n"
        "    updateOverviewCards: function() {\n"
        "        var activeElement = document.getElementById('activeRequests');\n"
        "        if (activeElement) {\n"
        "            activeElement.textContent = (this.data.requests.per_second || 0).toFixed(1);\n"
        "        }\n"
        "\n"
        "        var totalElement = document.getElementById('totalRequests');\n"
        "        if (totalElement) {\n"
        "            var total = this.data.requests.total_today || 0;\n"
        "            totalElement.textContent = this.formatNumber(total);\n"
        "        }\n"
        "\n"
        "        var successElement = document.getElementById('successRate');\n"
        "        if (successElement) {\n"
        "            successElement.textContent = this.calculateSuccessRate() + '%';\n"
        "        }\n"
        "\n"
        "        var uptimeElement = document.getElementById('uptime');\n"
        "        if (uptimeElement) {\n"
        "            var uptime = this.data.system.uptime_sec || 0;\n"
        "            uptimeElement.textContent = this.formatDuration(uptime);\n"
        "        }\n"
        "    },\n"
        "\n"
        "    updateProviderCards: function() {\n"
        "        var providersGrid = document.getElementById('providersGrid');\n"
        "        if (!providersGrid || !this.data.providers) return;\n"
        "\n"
        "        providersGrid.innerHTML = '';\n"
        "\n"
        "        for (var name in this.data.providers) {\n"
        "            var provider = this.data.providers[name];\n"
        "            var card = this.createProviderCard(name, provider);\n"
        "            providersGrid.appendChild(card);\n"
        "        }\n"
        "    },\n"
        "\n"
        "    createProviderCard: function(name, provider) {\n"
        "        var card = document.createElement('div');\n"
        "        card.className = 'provider-card';\n"
        "\n"
        "        var isHealthy = provider.healthy !== false;\n"
        "        var statusClass = provider.healthy === false ? 'unhealthy' : '';\n"
        "\n"
        "        card.innerHTML =\n"
        "            '<div class=\"provider-header\">' +\n"
        "            '<h3>' + this.capitalizeFirst(name) + '</h3>' +\n"
        "            '<div class=\"provider-status\">' +\n"
        "            '<div class=\"status-indicator ' + statusClass + '\"></div>' +\n"
        "            '<span>' + (isHealthy ? 'Healthy' : 'Unhealthy') + '</span>' +\n"
        "            '</div>' +\n"
        "            '</div>' +\n"
        "            '<div class=\"provider-metrics\">' +\n"
        "            '<div class=\"metric-row\">' +\n"
        "            '<span class=\"metric-label\">Response Time</span>' +\n"
        "            '<span class=\"metric-value-small\">' + (provider.response_time_ms || 0) + 'ms</span>' +\n"
        "            '</div>' +\n"
        "            '<div class=\"metric-row\">' +\n"
        "            '<span class=\"metric-label\">Success Rate</span>' +\n"
        "            '<span class=\"metric-value-small\">' + (provider.success_rate || 0) + '%</span>' +\n"
        "            '</div>' +\n"
        "            '<div class=\"metric-row\">' +\n"
        "            '<span class=\"metric-label\">Requests/min</span>' +\n"
        "            '<span class=\"metric-value-small\">' + (provider.requests_per_min || 0) + '</span>' +\n"
        "            '</div>' +\n"
        "            '</div>' +\n"
        "            '<div class=\"provider-actions\">' +\n"
        "            '<button class=\"btn btn-primary\" onclick=\"dashboard.testProvider(' + name + ')\">Test</button>' +\n"
        "            '<button class=\"btn btn-secondary\" onclick=\"dashboard.toggleProvider(' + name + ')\">Toggle</button>' +\n"
        "            '</div>';\n"
        "\n"
        "        return card;\n"
        "    },\n"
        "\n"
        "    updateSystemResources: function() {\n"
        "        var memoryUsage = this.data.system.memory_mb || 0;\n"
        "        var cpuUsage = this.data.system.cpu_percent || 0;\n"
        "\n"
        "        var memoryElement = document.getElementById('memoryUsage');\n"
        "        if (memoryElement) {\n"
        "            memoryElement.textContent = memoryUsage.toFixed(1) + ' MB';\n"
        "        }\n"
        "\n"
        "        var cpuElement = document.getElementById('cpuUsage');\n"
        "        if (cpuElement) {\n"
        "            cpuElement.textContent = cpuUsage.toFixed(1) + '%';\n"
        "        }\n"
        "    },\n"
        "\n"
        "    updateConnectionStatus: function(connected) {\n"
        "        var statusElement = document.getElementById('connectionStatus');\n"
        "        var statusDot = statusElement.querySelector('.status-dot');\n"
        "        var statusText = statusElement.querySelector('.status-text');\n"
        "\n"
        "        if (connected) {\n"
        "            statusElement.classList.remove('disconnected');\n"
        "            statusText.textContent = 'Connected';\n"
        "        } else {\n"
        "            statusElement.classList.add('disconnected');\n"
        "            statusText.textContent = 'Disconnected';\n"
        "        }\n"
        "    },\n"
        "\n"
        "    formatNumber: function(num) {\n"
        "        if (num >= 1000000) {\n"
        "            return (num / 1000000).toFixed(1) + 'M';\n"
        "        } else if (num >= 1000) {\n"
        "            return (num / 1000).toFixed(1) + 'K';\n"
        "        }\n"
        "        return num.toString();\n"
        "    },\n"
        "\n"
        "    formatDuration: function(seconds) {\n"
        "        if (seconds >= 3600) {\n"
        "            var hours = Math.floor(seconds / 3600);\n"
        "            var mins = Math.floor((seconds % 3600) / 60);\n"
        "            return hours + 'h ' + mins + 'm';\n"
        "        } else if (seconds >= 60) {\n"
        "            var mins = Math.floor(seconds / 60);\n"
        "            return mins + 'm';\n"
        "        }\n"
        "        return Math.floor(seconds) + 's';\n"
        "    },\n"
        "\n"
        "    capitalizeFirst: function(str) {\n"
        "        return str.charAt(0).toUpperCase() + str.slice(1);\n"
        "    },\n"
        "\n"
        "    calculateSuccessRate: function() {\n"
        "        if (!this.data.providers) return 0;\n"
        "\n"
        "        var totalSuccess = 0;\n"
        "        var providerCount = 0;\n"
        "\n"
        "        for (var name in this.data.providers) {\n"
        "            var provider = this.data.providers[name];\n"
        "            if (provider.success_rate !== undefined) {\n"
        "                totalSuccess += provider.success_rate;\n"
        "                providerCount++;\n"
        "            }\n"
        "        }\n"
        "\n"
        "        return providerCount > 0 ? Math.round(totalSuccess / providerCount) : 0;\n"
        "    },\n"
        "\n"
        "    testProvider: function(name) {\n"
        "        console.log('Testing provider:', name);\n"
        "        this.showNotification('Testing ' + name + '...', 'info');\n"
        "\n"
        "        fetch('/test', {\n"
        "            method: 'POST',\n"
        "            headers: {\n"
        "                'Content-Type': 'application/json'\n"
        "            },\n"
        "            body: JSON.stringify({\n"
        "                provider: name,\n"
        "                message: 'Hello from Aimux Dashboard!'\n"
        "            })\n"
        "        })\n"
        "        .then(function(response) {\n"
        "            return response.json();\n"
        "        })\n"
        "        .then(function(result) {\n"
        "            if (result.success) {\n"
        "                dashboard.showNotification(name + ' test successful', 'success');\n"
        "            } else {\n"
        "                dashboard.showNotification(name + ' test failed', 'error');\n"
        "            }\n"
        "        })\n"
        "        .catch(function(error) {\n"
        "            dashboard.showNotification('Test failed: ' + error.message, 'error');\n"
        "        });\n"
        "    },\n"
        "\n"
        "    toggleProvider: function(name) {\n"
        "        console.log('Toggle provider:', name);\n"
        "        this.showNotification('Toggle ' + name + ' - feature coming soon', 'info');\n"
        "    },\n"
        "\n"
        "    showNotification: function(message, type) {\n"
        "        console.log('[' + (type || 'info') + ']', message);\n"
        "\n"
        "        // Create notification element\n"
        "        var notification = document.createElement('div');\n"
        "        notification.className = 'notification notification-' + (type || 'info');\n"
        "        notification.textContent = message;\n"
        "\n"
        "        Object.assign(notification.style, {\n"
        "            position: 'fixed',\n"
        "            top: '20px',\n"
        "            right: '20px',\n"
        "            padding: '1rem 1.5rem',\n"
        "            borderRadius: '0.5rem',\n"
        "            backgroundColor: type === 'error' ? '#ef4444' :\n"
        "                             type === 'success' ? '#10b981' : '#2563eb',\n"
        "            color: 'white',\n"
        "            fontWeight: '500',\n"
        "            zIndex: '3000',\n"
        "            opacity: '0',\n"
        "            transform: 'translateX(100%)',\n"
        "            transition: 'all 0.3s ease'\n"
        "        });\n"
        "\n"
        "        document.body.appendChild(notification);\n"
        "\n"
        "        setTimeout(function() {\n"
        "            notification.style.opacity = '1';\n"
        "            notification.style.transform = 'translateX(0)';\n"
        "        }, 10);\n"
        "\n"
        "        setTimeout(function() {\n"
        "            notification.style.opacity = '0';\n"
        "            notification.style.transform = 'translateX(100%)';\n"
        "            setTimeout(function() {\n"
        "                if (notification.parentNode) {\n"
        "                    notification.parentNode.removeChild(notification);\n"
        "                }\n"
        "            }, 300);\n"
        "        }, 3000);\n"
        "    }\n"
        "};\n"
        "\n"
        "// Initialize when DOM is ready\n"
        "if (document.readyState === 'loading') {\n"
        "    document.addEventListener('DOMContentLoaded', function() {\n"
        "        dashboard.init();\n"
        "    });\n"
        "} else {\n"
        "    dashboard.init();\n"
        "}\n"
        "\n"
        "console.log('Aimux Dashboard loaded');\n";

    addResource("/dashboard.js", js, "application/javascript");
}

} // namespace webui
} // namespace aimux